# Generated by Django 5.1.4 on 2025-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
