# Generated by Django 5.1.4 on 2025-02-02 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_image'),
        ),
    ]
