# Generated by Django 5.1.5 on 2025-02-05 06:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dwbggpcgf/image/upload/v1738515996/oywv0ctnqnjvbi2ypcrt.png', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
