# Generated by Django 5.1.4 on 2025-01-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
