# Generated by Django 5.1.5 on 2025-02-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_employee_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('cloudinary_url', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tasks.taskdetail')),
            ],
        ),
    ]
