# Generated by Django 5.1.5 on 2025-02-06 08:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskasset',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='taskasset',
            name='file',
        ),
        migrations.AddField(
            model_name='taskasset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
